name: Deploy NestJS App to Cloud Run

env:
  SERVICE_NAME: nestjs-app
  DOCKER_IMAGE_NAME: server_image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file from PROD_ENV secret
        run: |
          echo "${{ secrets.PROD_ENV }}" > .env
          echo ".env file created with $(wc -l < .env) environment variables."

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker authentication
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/$DOCKER_IMAGE_NAME:latest ./backend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$DOCKER_IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          ENV_VARS=$(cat .env | grep -v '^#' | tr '\n' ',' | sed 's/,$//')
          gcloud run deploy $SERVICE_NAME --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/$DOCKER_IMAGE_NAME:latest --platform managed --region europe-central2 --allow-unauthenticated --port 80 --set-env-vars="$ENV_VARS"

